# Generated by Django 4.0.2 on 2022-03-09 15:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatChannel',
            fields=[
                ('channel_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('hp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('sprite', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('qrUrl', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30, null=True)),
                ('surname', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(max_length=40, null=True)),
                ('username', models.CharField(max_length=20)),
                ('pokemon_caught', models.IntegerField(default=0)),
                ('sprite_url', models.CharField(default='eugo\\static\\eugo\\img\teacher_sprites\teacher_1.png', max_length=100, null=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MapEvent',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('pos', models.CharField(max_length=100)),
                ('wildOrBattle', models.CharField(max_length=100)),
                ('lec_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eugo.lecturer')),
            ],
        ),
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lec_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eugo.lecturer')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eugo.player')),
            ],
        ),
        migrations.CreateModel(
            name='FriendsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.ManyToManyField(related_name='friends', to='eugo.Player')),
                ('user1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='eugo.player')),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='eugo.player')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='eugo.player')),
            ],
        ),
        migrations.CreateModel(
            name='CompleteEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eugo.mapevent')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eugo.player')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('content', models.CharField(default='message', max_length=100, null=True)),
                ('date', models.TimeField(default=django.utils.timezone.now)),
                ('channel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eugo.chatchannel')),
            ],
        ),
    ]
