# Generated by Django 4.0.2 on 2022-02-27 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('duration', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('hp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('sprite', models.CharField(max_length=100)),
                ('pos', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('wildOrBattle', models.CharField(max_length=100)),
                ('qrUrl', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30, null=True)),
                ('surname', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(max_length=40, null=True)),
                ('username', models.CharField(max_length=20)),
                ('pokemon_caught', models.IntegerField(default=0)),
                ('sprite_url', models.CharField(default='eugo\\static\\eugo\\img\teacher_sprites\teacher_1.png', max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lec_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eugo.lecturer')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eugo.player')),
            ],
        ),
    ]
