# Generated by Django 4.0.2 on 2022-03-01 15:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eugo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatChannel',
            fields=[
                ('channel_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='sprite_url',
            field=models.CharField(default='eugo\\static\\eugo\\img\teacher_sprites\teacher_1.png', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='chat_messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('channel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eugo.chatchannel')),
            ],
        ),
    ]
