# Generated by Django 4.0.2 on 2022-03-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eugo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='sprite_url',
            field=models.CharField(default='eugo\\static\\eugo\\img\teacher_sprites\teacher_1.png', max_length=100, null=True),
        ),
    ]
