# Generated by Django 4.0.2 on 2022-02-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eugo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='subject',
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='attack',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='hp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='lecID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='pos',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='sprite',
            field=models.CharField(max_length=100),
        ),
    ]
