# Generated by Django 4.0.2 on 2022-02-22 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eugo', '0002_remove_lecturer_subject_alter_lecturer_attack_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='lecID',
        ),
    ]
