# Generated by Django 4.0.2 on 2022-03-01 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eugo', '0002_chatchannel_alter_player_sprite_url_chat_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='chat_messages',
            new_name='chat_message',
        ),
    ]
