# Generated by Django 4.0.2 on 2022-03-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eugo', '0002_alter_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendslist',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends', to='eugo.Player'),
        ),
    ]
