# Generated by Django 4.0.2 on 2022-03-01 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eugo', '0002_alter_player_sprite_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='pos',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='wildOrBattle',
        ),
        migrations.CreateModel(
            name='MapEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.CharField(max_length=100)),
                ('wildOrBattle', models.CharField(max_length=100)),
                ('lec_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eugo.lecturer')),
            ],
        ),
    ]
