# Generated by Django 4.0.2 on 2022-03-01 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eugo', '0003_rename_chat_messages_chat_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='chat_message',
            new_name='ChatMessage',
        ),
    ]
