# Generated by Django 4.0.2 on 2022-02-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eugo', '0003_remove_lecturer_lecid'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='type',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecturer',
            name='wildOrBattle',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
