# Generated by Django 4.0.2 on 2022-02-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eugo', '0004_lecturer_type_lecturer_wildorbattle'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='qrUrl',
            field=models.CharField(default='https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=test', max_length=500),
            preserve_default=False,
        ),
    ]
