# Generated by Django 4.0.2 on 2022-02-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eugo', '0004_lecturer_type_lecturer_wildorbattle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
