# Generated by Django 4.0.2 on 2022-03-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eugo', '0004_rename_chat_message_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.CharField(default='message', max_length=100, null=True),
        ),
    ]
