# Generated by Django 4.0.2 on 2022-03-15 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eugo', '0004_alter_player_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendslist',
            name='friends',
        ),
        migrations.AddField(
            model_name='friendslist',
            name='friends',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='friendslist',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='eugo.player'),
        ),
    ]
