# Generated by Django 4.0.2 on 2022-03-09 17:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eugo', '0005_alter_mapevent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 3, 9, 17, 37, 23, 358618, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
