# Generated by Django 4.0.2 on 2022-03-21 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eugo', '0005_remove_friendslist_friends_friendslist_friends_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
