# Generated by Django 4.0.2 on 2022-02-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eugo', '0005_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturer',
            old_name='type',
            new_name='lecturer_type',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='wildOrBattle',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='is_wild',
            field=models.BooleanField(default=True),
        ),
    ]
