# Generated by Django 4.0.2 on 2022-03-01 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eugo', '0005_alter_chatmessage_content'),
        ('eugo', '0005_alter_mapevent_id'),
    ]

    operations = [
    ]
