# Generated by Django 4.0.2 on 2022-02-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eugo', '0006_rename_type_lecturer_lecturer_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='firstname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='salt',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='surname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
