# Generated by Django 4.0.2 on 2022-03-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eugo', '0006_merge_20220301_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='date',
            field=models.TimeField(),
        ),
    ]
