# Generated by Django 4.0.2 on 2022-02-25 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eugo', '0007_player_firstname_player_salt_player_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='email',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eugo.lecturer')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eugo.player')),
            ],
        ),
    ]
