# Generated by Django 4.0.2 on 2022-02-25 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eugo', '0006_alter_lecturer_id'),
        ('eugo', '0007_player_firstname_player_salt_player_surname'),
    ]

    operations = [
    ]
