# Generated by Django 4.0.2 on 2022-03-01 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eugo', '0007_alter_chatmessage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='date',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
