# Generated by Django 4.0.2 on 2022-02-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eugo', '0008_merge_20220225_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturer',
            old_name='lecturer_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='is_wild',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='wildOrBattle',
            field=models.CharField(default='battle', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='email',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
