# Generated by Django 4.0.2 on 2022-02-25 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eugo', '0008_player_email_hand'),
        ('eugo', '0009_rename_lecturer_type_lecturer_type_and_more'),
    ]

    operations = [
    ]
