# Generated by Django 4.0.2 on 2022-02-26 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eugo', '0010_merge_20220225_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hand',
            old_name='name',
            new_name='lec_id',
        ),
    ]
