# Generated by Django 4.0.2 on 2022-02-27 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eugo', '0010_merge_20220225_1709'),
        ('eugo', '0011_rename_name_hand_lec_id'),
    ]

    operations = [
    ]
