# Generated by Django 4.0.2 on 2022-02-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eugo', '0012_merge_20220227_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='password',
        ),
        migrations.RemoveField(
            model_name='player',
            name='salt',
        ),
        migrations.AddField(
            model_name='player',
            name='pokemon_caught',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='sprite_url',
            field=models.CharField(default='eugo\\static\\eugo\\img\teacher_sprites\teacher_1.png', max_length=100),
        ),
    ]
