# Generated by Django 4.0.2 on 2022-02-27 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eugo', '0013_player_pokemon_caught_player_sprite_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='password',
        ),
        migrations.RemoveField(
            model_name='player',
            name='salt',
        ),
    ]
